import RiemannHypothesisLean.Symmetry

/-!
# Conditional four-point zero orbit

This module proves the ordinary-zeta reflection step inside the critical strip by passing through
the completed zeta function. It then derives the familiar four-point orbit conditionally on the
two dependencies that remain explicit in the project: critical-strip localization and ordinary
zeta's compatibility with complex conjugation.
-/

open Complex

namespace RiemannHypothesisLean

noncomputable section

/-- Complex conjugation preserves the open critical strip. -/
theorem InCriticalStrip.conjugationPoint {s : ℂ} (hs : InCriticalStrip s) :
    InCriticalStrip (conjugationPoint s) := by
  exact ⟨by simpa using hs.1, by simpa using hs.2⟩

/-- A zeta zero with positive real part is a zero of the completed zeta function.

The positivity hypothesis excludes both `s = 0` and the zeros of the real gamma factor. -/
theorem completedZetaZero_of_riemannZetaZero_of_re_pos {s : ℂ}
    (hz : riemannZeta s = 0) (hpos : 0 < s.re) : IsCompletedZetaZero s := by
  have hs0 : s ≠ 0 := by
    intro hs
    have hre := congrArg Complex.re hs
    simp at hre
    linarith
  have hGamma : Gammaℝ s ≠ 0 := Gammaℝ_ne_zero_of_re_pos hpos
  rw [riemannZeta_def_of_ne_zero hs0] at hz
  unfold IsCompletedZetaZero
  rcases div_eq_zero_iff.mp hz with hcompleted | hgamma
  · exact hcompleted
  · exact (hGamma hgamma).elim

/-- Ordinary zeta zeros reflect under `s ↦ 1 - s` once the source lies in the critical strip. -/
theorem riemannZetaZero_criticalReflection {s : ℂ}
    (hz : riemannZeta s = 0) (hstrip : InCriticalStrip s) :
    riemannZeta (criticalReflection s) = 0 := by
  have hcompleted : IsCompletedZetaZero s :=
    completedZetaZero_of_riemannZetaZero_of_re_pos hz hstrip.1
  have hcompleted' : IsCompletedZetaZero (criticalReflection s) :=
    (completedZetaZero_criticalReflection_iff s).2 hcompleted
  have hreflectPos : 0 < (criticalReflection s).re := by
    simpa using sub_pos.mpr hstrip.2
  have hreflect0 : criticalReflection s ≠ 0 := by
    intro hs
    have hre := congrArg Complex.re hs
    simp at hre
    linarith
  unfold IsCompletedZetaZero at hcompleted'
  rw [riemannZeta_def_of_ne_zero hreflect0, hcompleted']
  simp

/-- The four points generated by real-axis conjugation and critical reflection are zeta zeros. -/
structure RiemannZetaZeroOrbit (s : ℂ) : Prop where
  source : riemannZeta s = 0
  conjugate : riemannZeta (conjugationPoint s) = 0
  reflected : riemannZeta (criticalReflection s) = 0
  dual : riemannZeta (dualSymmetry s) = 0

/-- Critical-strip localization plus conjugation compatibility produces the full four-point orbit
of every project-level nontrivial zero. Both unresolved dependencies remain explicit arguments. -/
theorem riemannZetaZeroOrbit_of_localization_and_conjugation
    (hloc : CriticalStripLocalization)
    (hconj : RiemannZetaConjugationCompatibility) {s : ℂ}
    (hs : IsNontrivialZero s) : RiemannZetaZeroOrbit s := by
  have hstrip : InCriticalStrip s := hloc s hs
  have hzConjugate : riemannZeta (conjugationPoint s) = 0 :=
    riemannZeta_eq_zero_conjugationPoint hconj hs.riemannZeta_eq_zero
  have hzReflected : riemannZeta (criticalReflection s) = 0 :=
    riemannZetaZero_criticalReflection hs.riemannZeta_eq_zero hstrip
  have hzDual : riemannZeta (criticalReflection (conjugationPoint s)) = 0 :=
    riemannZetaZero_criticalReflection hzConjugate hstrip.conjugationPoint
  refine ⟨hs.riemannZeta_eq_zero, hzConjugate, hzReflected, ?_⟩
  simpa [criticalReflection, conjugationPoint, dualSymmetry] using hzDual

/-- Gate 1 reduced localization to the positive-real-part condition, so the four-point orbit has
the same smaller dependency surface. -/
theorem riemannZetaZeroOrbit_of_positiveRealPart_and_conjugation
    (hpos : PositiveRealPartForNontrivialZeros)
    (hconj : RiemannZetaConjugationCompatibility) {s : ℂ}
    (hs : IsNontrivialZero s) : RiemannZetaZeroOrbit s :=
  riemannZetaZeroOrbit_of_localization_and_conjugation
    (criticalStripLocalization_iff_positiveRealPart.mpr hpos) hconj hs

end

end RiemannHypothesisLean
