import RiemannHypothesisLean.Conjugation

/-!
# Four-point zero orbit

This module proves the ordinary-zeta reflection step inside the critical strip by passing through
the completed zeta function. Critical-strip localization and conjugation transport are both now
checked, so every project-level nontrivial zero has the full four-point zeta-zero orbit.
-/

open Complex

namespace RiemannHypothesisLean

noncomputable section

/-- Complex conjugation preserves the open critical strip. -/
theorem InCriticalStrip.conjugationPoint {s : ℂ} (hs : InCriticalStrip s) :
    InCriticalStrip (conjugationPoint s) := by
  exact ⟨by simpa using hs.1, by simpa using hs.2⟩

/-- A zeta zero with positive real part is a zero of the completed zeta function.

The positivity hypothesis excludes both `s = 0` and the zeros of the real gamma factor. -/
theorem completedZetaZero_of_riemannZetaZero_of_re_pos {s : ℂ}
    (hz : riemannZeta s = 0) (hpos : 0 < s.re) : IsCompletedZetaZero s := by
  have hs0 : s ≠ 0 := by
    intro hs
    have hre := congrArg Complex.re hs
    simp at hre
    linarith
  have hGamma : Gammaℝ s ≠ 0 := Gammaℝ_ne_zero_of_re_pos hpos
  rw [riemannZeta_def_of_ne_zero hs0] at hz
  unfold IsCompletedZetaZero
  rcases div_eq_zero_iff.mp hz with hcompleted | hgamma
  · exact hcompleted
  · exact (hGamma hgamma).elim

/-- Ordinary zeta zeros reflect under `s ↦ 1 - s` once the source lies in the critical strip. -/
theorem riemannZetaZero_criticalReflection {s : ℂ}
    (hz : riemannZeta s = 0) (hstrip : InCriticalStrip s) :
    riemannZeta (criticalReflection s) = 0 := by
  have hcompleted : IsCompletedZetaZero s :=
    completedZetaZero_of_riemannZetaZero_of_re_pos hz hstrip.1
  have hcompleted' : IsCompletedZetaZero (criticalReflection s) :=
    (completedZetaZero_criticalReflection_iff s).2 hcompleted
  have hreflectPos : 0 < (criticalReflection s).re := by
    simpa using sub_pos.mpr hstrip.2
  have hreflect0 : criticalReflection s ≠ 0 := by
    intro hs
    have hre : (criticalReflection s).re = 0 := by
      simpa using congrArg Complex.re hs
    exact (ne_of_gt hreflectPos) hre
  unfold IsCompletedZetaZero at hcompleted'
  rw [riemannZeta_def_of_ne_zero hreflect0, hcompleted']
  simp

/-- The four points generated by real-axis conjugation and critical reflection are zeta zeros. -/
structure RiemannZetaZeroOrbit (s : ℂ) : Prop where
  source : riemannZeta s = 0
  conjugate : riemannZeta (conjugationPoint s) = 0
  reflected : riemannZeta (criticalReflection s) = 0
  dual : riemannZeta (dualSymmetry s) = 0

/-- Critical-strip localization produces the full four-point orbit of every project-level
nontrivial zero. -/
theorem riemannZetaZeroOrbit_of_localization
    (hloc : CriticalStripLocalization) {s : ℂ}
    (hs : IsNontrivialZero s) : RiemannZetaZeroOrbit s := by
  have hstrip : InCriticalStrip s := hloc s hs
  have hzConjugate : riemannZeta (conjugationPoint s) = 0 :=
    hs.riemannZeta_conjugationPoint_eq_zero
  have hzReflected : riemannZeta (criticalReflection s) = 0 :=
    riemannZetaZero_criticalReflection hs.riemannZeta_eq_zero hstrip
  have hzDual : riemannZeta (criticalReflection (conjugationPoint s)) = 0 :=
    riemannZetaZero_criticalReflection hzConjugate hstrip.conjugationPoint
  refine ⟨hs.riemannZeta_eq_zero, hzConjugate, hzReflected, ?_⟩
  simpa [criticalReflection, conjugationPoint, dualSymmetry] using hzDual

/-- The positive-real-part formulation is an equivalent input interface for the orbit theorem. -/
theorem riemannZetaZeroOrbit_of_positiveRealPart
    (hpos : PositiveRealPartForNontrivialZeros) {s : ℂ}
    (hs : IsNontrivialZero s) : RiemannZetaZeroOrbit s :=
  riemannZetaZeroOrbit_of_localization
    (criticalStripLocalization_iff_positiveRealPart.mpr hpos) hs

/-- Every project-level nontrivial zero has the expected four-point zeta-zero orbit. -/
theorem IsNontrivialZero.riemannZetaZeroOrbit {s : ℂ}
    (hs : IsNontrivialZero s) : RiemannZetaZeroOrbit s :=
  riemannZetaZeroOrbit_of_localization criticalStripLocalization hs

end

end RiemannHypothesisLean
